# Copyright 2025 iceberg-compaction
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Setup Rust Builder
description: 'Setup Rust Build Environment'
inputs:
  rust-version:
    description: 'Version of Rust to install (leave empty to use rust-toolchain.toml)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup specified Rust toolchain
      shell: bash
      if: ${{ inputs.rust-version != '' }}
      env:
        RUST_VERSION: ${{ inputs.rust-version }}
      run: |
        echo "Installing Rust ${RUST_VERSION}"
        rustup toolchain install ${RUST_VERSION}
        rustup override set ${RUST_VERSION}
        rustup component add rustfmt clippy

    - name: Setup Rust toolchain from rust-toolchain.toml
      shell: bash
      if: ${{ inputs.rust-version == '' }}
      run: |
        echo "Installing toolchain from rust-toolchain.toml"
        rustup show
        rustup component add rustfmt clippy
